FROM python:3-alpine
MAINTAINER Pascal Molin <pascal.molin@u-paris.fr>
WORKDIR /usr/src/app
RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir requests==2.28.1 \
  && pip install --no-cache-dir unidecode
